package com.farmafriend.erp.constants;

public enum ProductCategory {
	SEEDS, 
	FERTILIZERS,
	PESTICIDES, 
	FUNGICIDES,
	HERBICIDES, 
	PLANT_GROWTH_REGULATORS, 
	MICRONUTRIENTS, 
	BIO_FERTILIZERS,
	DRIP_IRRIGATION, SPRAYERS, 
	IRRIGATION_EQUIPMENT, 
	FARM_TOOLS,
	AGRICULTURAL_MACHINERY,
	ANIMAL_FEED, 
	VETERINARY_PRODUCTS,
	ORGANIC_FARMING, 
	GREENHOUSE_SUPPLIES, 
	HARVESTING_EQUIPMENT,
	STORAGE_PRODUCTS, 
	GARDENING_PRODUCTS
}
